// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE9eCFArAJ4dnE7QVHrrlqKJox0Bb7wdE',
    appId: '1:16664813984:web:add547383569b00a6e84c5',
    messagingSenderId: '16664813984',
    projectId: 'shopywellfirestore',
    authDomain: 'shopywellfirestore.firebaseapp.com',
    storageBucket: 'shopywellfirestore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZIELeu_aXUieZ7DsWeZi7sGUWUQTJKM',
    appId: '1:16664813984:android:2da3bab6fe5a36856e84c5',
    messagingSenderId: '16664813984',
    projectId: 'shopywellfirestore',
    storageBucket: 'shopywellfirestore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlD3IxoyQrGCn1jifobER5dazGp9KBs7s',
    appId: '1:16664813984:ios:2891f4e58f09c67b6e84c5',
    messagingSenderId: '16664813984',
    projectId: 'shopywellfirestore',
    storageBucket: 'shopywellfirestore.firebasestorage.app',
    iosBundleId: 'com.shopywell.shopywell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlD3IxoyQrGCn1jifobER5dazGp9KBs7s',
    appId: '1:16664813984:ios:2891f4e58f09c67b6e84c5',
    messagingSenderId: '16664813984',
    projectId: 'shopywellfirestore',
    storageBucket: 'shopywellfirestore.firebasestorage.app',
    iosBundleId: 'com.shopywell.shopywell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE9eCFArAJ4dnE7QVHrrlqKJox0Bb7wdE',
    appId: '1:16664813984:web:ff6a917cf1e540556e84c5',
    messagingSenderId: '16664813984',
    projectId: 'shopywellfirestore',
    authDomain: 'shopywellfirestore.firebaseapp.com',
    storageBucket: 'shopywellfirestore.firebasestorage.app',
  );
}
